version: "3.8"

services:
  mongodb:
    image: docker.io/mongodb/mongodb-community-server:latest
    restart: unless-stopped
    logging:
      options:
        max-size: 1g
    env_file: ./.env
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGODB_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro 
  app:
    depends_on:
      - mongodb
    build: ./../../OpenAPI-SQM
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - DB_URL=mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongodb:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin&authMechanism=DEFAULT
    stdin_open: true
    tty: true
volumes:
  db: